// Quick links mapping by university
export const universityLinks: Record<string, Array<{ label: string; url: string }>> = {
  'Brigham Young University': [
    { label: 'Home', url: 'https://www.byu.edu/' },
    { label: '2026 Calendar', url: 'https://academiccalendar.byu.edu/?y=2026' },
    { label: 'MyBYU', url: 'https://my.byu.edu/' },
    { label: 'Record Summary', url: 'https://y.byu.edu/ry/ae/prod/records/cgi/stdCourseWork.cgi' },
    { label: 'MyMap W2026', url: 'https://commtech.byu.edu/auth/mymap/?yearTerm=20261&proxyId=509241872#/' },
    { label: 'Financial Center', url: 'https://sa.byu.edu/psc/ps/EMPLOYEE/SA/c/Y_MY_FINANCIAL_CENTER.Y_MFC_HOME_V2_FL.GBL?Page=Y_MFC_HOME_V2_FL&EMPLID=247348708&OPRID=ins0417&' },
    { label: 'BYU Outlook', url: 'https://outlook.office.com/mail/' },
    { label: 'BYU Library', url: 'https://lib.byu.edu/' },
    { label: 'Residence Life', url: 'https://reslife.byu.edu/' },
    { label: 'Endorsement', url: 'https://endorse.byu.edu/' },
    { label: 'Textbooks', url: 'https://booklist.byu.edu/' },
  ],
  'Brigham Young University Idaho': [
    { label: 'Home', url: 'https://www.byui.edu/' },
    { label: 'Calendar', url: 'https://www.byui.edu/academic-calendar' },
    { label: 'myBYUI', url: 'https://my.byui.edu/' },
    { label: 'Records Summary', url: 'https://my.byui.edu/student-records' },
    { label: 'Degree Planner', url: 'https://my.byui.edu/degree-planner' },
    { label: 'Financial Center', url: 'https://my.byui.edu/finances' },
    { label: 'BYUI Outlook', url: 'https://outlook.office.com/mail/' },
    { label: 'BYUI Library', url: 'https://library.byui.edu/' },
    { label: 'BYUI Student Living', url: 'https://www.byui.edu/student-living' },
    { label: 'Endorsements', url: 'https://www.byui.edu/student-honor-office/endorsements' },
    { label: 'Advising', url: 'https://www.byui.edu/advising' },
    { label: 'Career Services', url: 'https://www.byui.edu/career-services' },
  ],
  'Brigham Young University Hawaii': [
    { label: 'Home', url: 'https://www.byuh.edu/' },
    { label: 'Calendar', url: 'https://registrar.byuh.edu/academic-calendar' },
    { label: 'myBYUH', url: 'https://my.byuh.edu/' },
    { label: 'Records Summary', url: 'https://my.byuh.edu/student-records' },
    { label: 'Degree Audit', url: 'https://my.byuh.edu/degree-audit' },
    { label: 'Financial Center', url: 'https://my.byuh.edu/financial-services' },
    { label: 'BYUH Outlook', url: 'https://outlook.office.com/mail/' },
    { label: 'BYUH Library', url: 'https://library.byuh.edu/' },
    { label: 'Student Housing', url: 'https://housing.byuh.edu/' },
    { label: 'Endorsements', url: 'https://endorse.byuh.edu/' },
    { label: 'Advising Center', url: 'https://advising.byuh.edu/' },
    { label: 'Career Services', url: 'https://career.byuh.edu/' },
  ],
  'UNC Chapel Hill': [
    { label: 'Home', url: 'https://www.unc.edu/' },
    { label: 'Calendar', url: 'https://registrar.unc.edu/academic-calendar/' },
    { label: 'MyCarolina', url: 'https://mycarolina.unc.edu/' },
    { label: 'Student Records', url: 'https://connectcarolina.unc.edu/' },
    { label: 'UNC Outlook', url: 'https://outlook.office.com/' },
    { label: 'UNC Libraries', url: 'https://library.unc.edu/' },
    { label: 'Housing', url: 'https://housing.unc.edu/' },
    { label: 'Registration', url: 'https://connectcarolina.unc.edu/' },
    { label: 'Advising Center', url: 'https://advising.unc.edu/' },
    { label: 'Career Center', url: 'https://careers.unc.edu/' },
  ],
  'Utah State University': [
    { label: 'Home', url: 'https://www.usu.edu/' },
    { label: 'Calendar', url: 'https://www.usu.edu/registrar/calendars' },
    { label: 'myUSU', url: 'https://my.usu.edu/' },
    { label: 'Student Records', url: 'https://my.usu.edu/' },
    { label: 'Degree Audit', url: 'https://my.usu.edu/' },
    { label: 'Financial Center', url: 'https://my.usu.edu/' },
    { label: 'USU Outlook', url: 'https://outlook.office.com/' },
    { label: 'USU Library', url: 'https://library.usu.edu/' },
    { label: 'Housing Services', url: 'https://www.usu.edu/housing/' },
    { label: 'Registrar', url: 'https://www.usu.edu/registrar/' },
    { label: 'Advising Center', url: 'https://www.usu.edu/advising/' },
    { label: 'Career Center', url: 'https://www.usu.edu/career/' },
  ],
  'Utah Valley University': [
    { label: 'Home', url: 'https://www.uvu.edu/' },
    { label: 'Calendar', url: 'https://www.uvu.edu/registrar/academic-calendars/' },
    { label: 'myUVU', url: 'https://my.uvu.edu/' },
    { label: 'Student Records', url: 'https://my.uvu.edu/' },
    { label: 'Degree Audit', url: 'https://my.uvu.edu/' },
    { label: 'Financial Center', url: 'https://my.uvu.edu/' },
    { label: 'UVU Outlook', url: 'https://outlook.office.com/' },
    { label: 'UVU Library', url: 'https://www.uvu.edu/library/' },
    { label: 'Housing', url: 'https://www.uvu.edu/housing/' },
    { label: 'Registrar', url: 'https://www.uvu.edu/registrar/' },
    { label: 'Advising Center', url: 'https://www.uvu.edu/advising/' },
    { label: 'Career Center', url: 'https://www.uvu.edu/career/' },
  ],
};

export function getQuickLinks(university: string | null | undefined): Array<{ label: string; url: string }> {
  if (!university || !universityLinks[university]) {
    return [];
  }
  return universityLinks[university];
}
